### ISSUE TITLE
mislabelled meme/missing information

### ISSUE THREAD

**Issue by daank-c** [ShibeMagazine/media-hub#6]
I noticed that ya'll are missing the image for file for `meme_id:7` which means `dog007.md` should actually be `dog008.md`  and `dog007.md` needs to be added. OMG WHAT ARE WE GUNNA DO. 😭

**Comment by ShibeMagazine** [comment]
We need to freshen this up and add the missing information immediately before we look like idiots.

Would you be willing to take this on chachi?

**Comment by daank-c** [comment]
I could, but it would be way cooler if we started a special task force for librarian stuff.

**Comment by ShibeMagazine** [comment]
Ur a genius. Great idea. 🔥

**Comment by daank-c** [comment]
No u are.
![Screenshot 2023-01-09 11 35 37 PM](https://user-images.githubusercontent.com/102710924/211456415-8858903f-9e6c-44f6-845b-7a00edceb16d.png)

**Comment by ShibeMagazine** [comment]
This issue has been fixed via Commit: Issue Fixed #8
